# Generated by Django 4.2.2 on 2023-06-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_matiere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matiere',
        ),
    ]
