# Generated by Django 4.2.2 on 2023-06-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_delete_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
