# Generated by Django 4.2.2 on 2023-07-01 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_subject_code_subject_label_subject_total_times_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
