# Generated by Django 4.2.2 on 2023-07-01 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_delete_role'),
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Auth.level'),
        ),
        migrations.AlterField(
            model_name='timestable',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.level'),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
