# Generated by Django 4.2.2 on 2023-07-01 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_subject_level_alter_timestable_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestable',
            old_name='user',
            new_name='teacher',
        ),
    ]
