# Generated by Django 4.2.2 on 2023-07-01 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_user_timestable_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestable',
            old_name='week',
            new_name='week_num',
        ),
    ]
