# Generated by Django 4.2.2 on 2023-06-28 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0004_classroom_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='App.level')),
            ],
        ),
    ]
