# Generated by Django 4.2.2 on 2023-07-01 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='Level',
            new_name='level',
        ),
    ]
