# Generated by Django 4.2.2 on 2023-07-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_myuser_photo_de_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='photo_de_profil',
        ),
    ]
